In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [62]:
## DIQ_E is under: Questionnaire Data -> Diabetes
df_db = pd.read_sas('CDC_data/DIQ_E.XPT')
# demography    ## Demographic data
df_demo = pd.read_sas('CDC_data/DEMO_E.XPT')
# body measurements (BMI, height, waist)  ## examination data
df_bmx = pd.read_sas('CDC_data/BMX_E.XPT')
# Blood pressure  ## examination data
df_bpx = pd.read_sas('CDC_data/BPX_E.XPT')
# LDL Cholesterol Measurements  ##laboratory data
df_ldl = pd.read_sas('CDC_data/TRIGLY_E.XPT')
# Glucohemoglobin level   ##laboratory data
df_gh = pd.read_sas('CDC_data/GHB_E.XPT')
#smoke
df_smx = pd.read_sas('CDC_data/SMQ_E.XPT')

# Has heart desease 
df_hd = pd.read_csv('has_heart_disease.csv', index_col=0)

year_freq = df_hd.groupby('HasHeartDisease').count()
year_freq

                 SEQN
HasHeartDisease
0                5653
1                 253

In [68]:
df_master = df_db.merge(df_demo, on='SEQN', how='inner')
df_master = df_master.merge(df_bmx, on='SEQN', how='inner')
df_master = df_master.merge(df_bpx, on='SEQN', how='inner')
df_master = df_master.merge(df_ldl, on='SEQN', how='inner')
df_master = df_master.merge(df_hd, on='SEQN', how='inner')
df_master = df_master.merge(df_gh, on='SEQN', how='inner')
df_master = df_master.merge(df_smx, on='SEQN', how='inner')

In [69]:
key_columns = ['SEQN','HasHeartDisease', 'SMD650', 'RIDAGEYR', 'DMQMILIT', 'DMDHRAGE', 'DIQ190C', 'SMD057','LBDLDL','DIQ050','LBXGH','BMIWT','DIQ010','BPXML1', 'SMD100FL', 'BPXPULS']
df_master = df_master[key_columns]
# df_master.rename(columns={'DIQ010': 'Diagnose', 'DID040': "Age diagnosed", 'DIQ160': 'Prediabetes', 'DIQ170':'Risk for DB', 
#                           'RIAGENDR': 'Gender', 'RIDAGEYR': "Age", 'RIDRETH1': 'Race/Ethnicity', 'RIDEXPRG':'Pregnancy status',
#                          'BMXWAIST': "Waist", 'BMXBMI': "BMI", 'LBDHDD': 'HDL Chol', 'LBDLDL': 'LDL Chol', 'LBXGH':'Glucohem'}, inplace=True)
df_master

,SEQN,HasHeartDisease,SMD650,RIDAGEYR,DMQMILIT,DMDHRAGE,DIQ190C,SMD057,LBDLDL,DIQ050,LBXGH,BMIWT,DIQ010,BPXML1,SMD100FL,BPXPULS
0,41479.0,0,NaN,52.0,2.0,52.0,2.0,NaN,121.0,2.0,5.7,NaN,2.0,140.0,NaN,1.0
1,41481.0,0,NaN,21.0,2.0,51.0,2.0,NaN,NaN,2.0,NaN,NaN,2.0,140.0,NaN,1.0
2,41485.0,0,NaN,30.0,2.0,30.0,2.0,NaN,119.0,2.0,5.5,NaN,2.0,140.0,NaN,1.0
3,41486.0,0,NaN,61.0,2.0,67.0,1.0,NaN,110.0,2.0,6.1,NaN,2.0,150.0,NaN,1.0
4,41487.0,0,NaN,27.0,2.0,26.0,2.0,NaN,105.0,2.0,5.0,NaN,2.0,150.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2758,51616.0,0,10.0,60.0,2.0,60.0,1.0,NaN,76.0,1.0,7.3,NaN,1.0,190.0,1.0,2.0
2759,51617.0,0,NaN,71.0,2.0,71.0,2.0,NaN,88.0,2.0,6.0,NaN,2.0,150.0,NaN,1.0
2760,51618.0,0,NaN,48.0,2.0,48.0,2.0,NaN,124.0,2.0,5.6,NaN,2.0,160.0,NaN,1.0
2761,51620.0,0,NaN,50.0,2.0,51.0,2.0,40.0,158.0,2.0,5.4,NaN,2.0,140.0,NaN,1.0
2762,51623.0,1,1.0,72.0,2.0,72.0,1.0,NaN,61.0,2.0,5.4,NaN,2.0,150.0,1.0,1.0

In [73]:
df_master.corr()['HasHeartDisease'].abs().sort_values(ascending=False)

HasHeartDisease    1.000000
SMD650             0.285578
RIDAGEYR           0.211372
DMQMILIT           0.199856
DMDHRAGE           0.180374
DIQ190C            0.162494
SMD057             0.144296
LBDLDL             0.139395
DIQ050             0.135957
LBXGH              0.128351
BMIWT              0.120866
DIQ010             0.119343
BPXML1             0.112253
SMD100FL           0.111544
BPXPULS            0.105845
SEQN               0.021011
Name: HasHeartDisease, dtype: float64

In [77]:
df_master.to_csv('heart_disease_merged.csv')